"""
pipeline/graph_query.py — Natural Language Query Engine for the System Knowledge Graph

Translates plain-English questions into graph queries and returns human-readable
answers.  Works in two modes depending on what's available:

  Mode A — Neo4j (preferred)
    Converts NL → Cypher via LLM → executes against Neo4j → formats result.
    Requires NEO4J_URI env var and a running Neo4j instance.

  Mode B — JSON fallback (offline)
    Converts NL → structured filter via LLM → executes against knowledge_graph.json
    in pure Python.  No external services required.

The LLM is grounded on the *actual* schema extracted from the graph file
(node labels, relationship types, example node IDs) so it cannot hallucinate
relationship names like [:IMPLEMENTED_BY] that don't exist.

Usage (programmatic):
    from pipeline.graph_query import GraphQueryEngine

    engine = GraphQueryEngine(context_file="outputs/run_.../context.json")
    result = engine.query("Which features depend on login?")
    print(result.answer)
    print(result.query_used)

Usage (CLI via run_query.py):
    python run_query.py --resume outputs/run_.../context.json
    python run_query.py --resume outputs/run_.../context.json \\
                        --ask "Which features depend on login?"
"""

from __future__ import annotations

import json
import os
import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from context import PipelineContext
from pipeline.llm_client import call_llm

# ── Constants ──────────────────────────────────────────────────────────────────

# Max raw graph nodes to include as schema examples (keeps prompt bounded)
_MAX_EXAMPLE_NODES = 12
# Max rows to include in the formatted answer
_MAX_RESULT_ROWS   = 30
# Cypher generation token budget (query only — tight on purpose)
_CYPHER_MAX_TOKENS = 512
# Answer formatting token budget
_FORMAT_MAX_TOKENS = 1024
# JSON filter generation token budget
_FILTER_MAX_TOKENS = 512


# ── Public Data Classes ────────────────────────────────────────────────────────

@dataclass
class QueryResult:
    """
    The complete output of a single NL → graph query.

    Attributes:
        question      The original natural-language question
        mode          "neo4j" | "json"
        query_used    The Cypher or JSON-filter string generated by the LLM
        raw_rows      Raw result rows from the graph backend
        answer        Human-readable formatted answer
        error         Non-None if the query failed
    """
    question:   str
    mode:       str                  = "json"
    query_used: str                  = ""
    raw_rows:   list[dict[str, Any]] = field(default_factory=list)
    answer:     str                  = ""
    error:      str | None           = None


@dataclass
class GraphSchema:
    """
    Schema extracted from knowledge_graph.json for LLM grounding.
    Injected into every Cypher/filter generation prompt so the LLM
    cannot hallucinate relationship types or node labels.
    """
    node_labels:    list[str]         # e.g. ["Actor", "BoundedContext", "Feature", ...]
    rel_types:      list[str]         # e.g. ["ACTOR_PERFORMS", "ENTITY_STORED_IN", ...]
    example_nodes:  list[dict]        # [{id, label, type}, ...]
    run_id:         str               = ""
    domain_name:    str               = ""


# ── Main Engine ────────────────────────────────────────────────────────────────

class GraphQueryEngine:
    """
    Natural-language query engine over the system knowledge graph.

    Instantiate once, call query() as many times as needed.

        engine = GraphQueryEngine(context_file="outputs/run_.../context.json")
        result = engine.query("What tables does the checkout flow write?")
    """

    def __init__(self, context_file: str) -> None:
        """
        Args:
            context_file: Path to context.json from a completed pipeline run.

        Raises:
            FileNotFoundError: If context.json or knowledge_graph.json is missing.
            RuntimeError: If Stage 9 has not been completed.
        """
        ctx = PipelineContext.load(context_file)

        if not ctx.is_stage_done("stage9_knowledge_graph"):
            raise RuntimeError(
                "Stage 9 (knowledge graph) has not been completed.\n"
                f"Run: python run_stage9.py --resume {context_file}"
            )

        kg_path = ctx.knowledge_graph_meta.json_path
        if not Path(kg_path).exists():
            raise RuntimeError(f"knowledge_graph.json not found: {kg_path}")

        self._ctx       = ctx
        self._kg_path   = kg_path
        self._graph     = self._load_graph()
        self._schema    = self._extract_schema()
        self._neo4j_cfg = self._detect_neo4j()
        self._run_id    = ctx.run_id

        mode = "neo4j" if self._neo4j_cfg else "json (offline)"
        print(f"[graph_query] Engine ready  mode={mode}  "
              f"nodes={len(self._graph['nodes'])}  "
              f"edges={len(self._graph['edges'])}")

    # ── Public API ─────────────────────────────────────────────────────────────

    def query(self, question: str) -> QueryResult:
        """
        Translate a natural-language question and return a QueryResult.

        The method selects the appropriate backend (Neo4j or JSON), generates
        a query with the LLM, executes it, and formats the answer.

        Args:
            question: Plain English question, e.g. "Which features depend on login?"

        Returns:
            QueryResult with .answer populated.  Never raises — errors are
            captured in QueryResult.error.
        """
        print(f"[graph_query] Question: {question!r}")

        if self._neo4j_cfg:
            return self._query_neo4j(question)
        else:
            return self._query_json(question)

    def schema_summary(self) -> str:
        """Return a human-readable summary of the graph schema."""
        s = self._schema
        lines = [
            f"Domain       : {s.domain_name}",
            f"Run ID       : {s.run_id}",
            f"Node labels  : {', '.join(s.node_labels)}",
            f"Rel types    : {', '.join(s.rel_types)}",
            f"Example nodes:",
        ]
        for n in s.example_nodes[:8]:
            lines.append(f"  [{n['type']}] {n['label']}  (id: {n['id']})")
        return "\n".join(lines)

    # ── Neo4j Path ─────────────────────────────────────────────────────────────

    def _query_neo4j(self, question: str) -> QueryResult:
        """NL → Cypher → Neo4j → formatted answer."""
        result = QueryResult(question=question, mode="neo4j")

        # Step 1: NL → Cypher
        cypher = self._generate_cypher(question)
        result.query_used = cypher
        print(f"[graph_query] Cypher: {cypher}")

        if not cypher:
            result.error  = "LLM did not produce a Cypher query."
            result.answer = "Sorry, I couldn't translate that question into a graph query."
            return result

        # Step 2: Execute Cypher
        try:
            rows = self._run_cypher(cypher)
            result.raw_rows = rows
        except Exception as exc:
            result.error  = f"Cypher execution failed: {exc}"
            result.answer = (
                f"The query ran into an error:\n  {exc}\n\n"
                f"Generated Cypher was:\n{cypher}"
            )
            return result

        # Step 3: Format answer
        result.answer = self._format_answer(question, cypher, rows)
        return result

    def _generate_cypher(self, question: str) -> str:
        """
        Ask the LLM to convert a natural-language question to Cypher.
        Returns the Cypher string, or "" on failure.
        """
        system = self._cypher_system_prompt()
        user   = (
            f"Question: {question}\n\n"
            f"Return ONLY the Cypher query. "
            f"No explanation, no markdown fences, no LIMIT unless the question asks for it."
        )
        raw = call_llm(system, user, max_tokens=_CYPHER_MAX_TOKENS,
                       label="graph_query_cypher")

        # Strip accidental fences or leading/trailing whitespace
        cypher = raw.strip()
        cypher = re.sub(r"^```(?:cypher)?\s*", "", cypher, flags=re.IGNORECASE)
        cypher = re.sub(r"\s*```$", "", cypher)
        return cypher.strip()

    def _run_cypher(self, cypher: str) -> list[dict[str, Any]]:
        """Execute a Cypher query against Neo4j and return rows as dicts."""
        from neo4j import GraphDatabase

        uri, user, passw, db = self._neo4j_cfg
        driver = GraphDatabase.driver(uri, auth=(user, passw))
        rows: list[dict] = []
        try:
            with driver.session(database=db) as session:
                result = session.run(cypher, run_id=self._run_id)
                for record in result:
                    row = {}
                    for key in record.keys():
                        val = record[key]
                        # Flatten Neo4j Node objects to their properties
                        if hasattr(val, "_properties"):
                            row[key] = dict(val._properties)
                        else:
                            row[key] = val
                    rows.append(row)
        finally:
            driver.close()
        return rows

    # ── JSON Fallback Path ─────────────────────────────────────────────────────

    def _query_json(self, question: str) -> QueryResult:
        """
        NL → structured JSON filter → Python execution against in-memory graph.
        Used when Neo4j is not configured.
        """
        result = QueryResult(question=question, mode="json")

        # Step 1: NL → filter spec
        filter_spec = self._generate_json_filter(question)
        result.query_used = json.dumps(filter_spec, indent=2)
        print(f"[graph_query] JSON filter: {result.query_used}")

        if not filter_spec:
            result.error  = "LLM did not produce a filter spec."
            result.answer = "Sorry, I couldn't translate that question into a graph query."
            return result

        # Step 2: Execute filter
        try:
            rows = self._run_json_filter(filter_spec)
            result.raw_rows = rows
        except Exception as exc:
            result.error  = f"JSON filter execution failed: {exc}"
            result.answer = f"Query failed: {exc}"
            return result

        # Step 3: Format answer
        result.answer = self._format_answer(
            question, json.dumps(filter_spec), rows
        )
        return result

    def _generate_json_filter(self, question: str) -> dict[str, Any]:
        """
        Ask the LLM to produce a JSON filter spec that describes how to
        traverse the in-memory graph to answer the question.

        Filter spec schema:
        {
          "start_type":    "feature",         # node type to start from
          "start_label":   "login",           # label substring match (case-insensitive)
          "traverse":      [                  # 0+ hops to follow
            {"edge_type": "feature_includes", "direction": "out"},
            {"edge_type": "flow_uses",        "direction": "out"}
          ],
          "return_type":   "page",            # type of nodes to collect at the end
          "return_field":  "label"            # field to extract from result nodes
        }
        """
        system = self._json_filter_system_prompt()
        user   = (
            f"Question: {question}\n\n"
            f"Return ONLY the JSON filter object. "
            f"No explanation, no markdown fences."
        )
        raw = call_llm(system, user, max_tokens=_FILTER_MAX_TOKENS,
                       label="graph_query_filter")

        raw = raw.strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.IGNORECASE)
        raw = re.sub(r"\s*```$", "", raw)

        try:
            spec = json.loads(raw)
            if isinstance(spec, dict):
                return spec
        except json.JSONDecodeError:
            # Try to extract first { ... } block
            m = re.search(r"\{.*\}", raw, re.DOTALL)
            if m:
                try:
                    return json.loads(m.group())
                except json.JSONDecodeError:
                    pass
        return {}

    def _run_json_filter(self, spec: dict) -> list[dict[str, Any]]:
        """
        Execute a JSON filter spec against self._graph using pure Python.

        Traversal is BFS: start at nodes matching start_type + start_label,
        follow the edge_type hops in order, collect return_type nodes at the end.
        """
        nodes_by_id   = {n["id"]: n for n in self._graph["nodes"]}
        edges         = self._graph["edges"]

        # Build adjacency index: (source_id, edge_type) → [target_id]
        # and                    (target_id, edge_type) → [source_id]  for "in" direction
        adj_out: dict[tuple, list[str]] = {}
        adj_in:  dict[tuple, list[str]] = {}
        for edge in edges:
            src = edge["source"]
            dst = edge["target"]
            et  = edge["type"]
            adj_out.setdefault((src, et), []).append(dst)
            adj_in.setdefault((dst, et),  []).append(src)

        # Seed: find start nodes
        start_type  = spec.get("start_type", "").lower()
        start_label = spec.get("start_label", "").lower()

        current_ids: list[str] = [
            n["id"]
            for n in self._graph["nodes"]
            if (not start_type  or n.get("type",  "").lower() == start_type)
            and (not start_label or start_label in n.get("label", "").lower())
        ]

        if not current_ids:
            return []

        # Traverse hops
        for hop in spec.get("traverse", []):
            et        = hop.get("edge_type", "")
            direction = hop.get("direction", "out")
            adj       = adj_out if direction == "out" else adj_in
            next_ids: list[str] = []
            for nid in current_ids:
                next_ids.extend(adj.get((nid, et), []))
            current_ids = list(dict.fromkeys(next_ids))  # deduplicate, preserve order

        # Collect result nodes, optionally filtering by return_type
        return_type  = spec.get("return_type",  "").lower()
        return_field = spec.get("return_field", "label")

        results: list[dict] = []
        for nid in current_ids:
            node = nodes_by_id.get(nid)
            if not node:
                continue
            if return_type and node.get("type", "").lower() != return_type:
                continue
            results.append({
                "type":  node.get("type", ""),
                "label": node.get("label", nid),
                "value": node.get(return_field, node.get("label", nid)),
                "id":    nid,
            })

        return results[:_MAX_RESULT_ROWS]

    # ── Answer Formatting ──────────────────────────────────────────────────────

    def _format_answer(
        self,
        question: str,
        query:    str,
        rows:     list[dict[str, Any]],
    ) -> str:
        """
        Ask the LLM to produce a concise natural-language answer from raw rows.
        Falls back to a plain table if LLM formatting fails.
        """
        if not rows:
            return "No results found for that question."

        rows_preview = rows[:_MAX_RESULT_ROWS]
        rows_text    = json.dumps(rows_preview, indent=2, ensure_ascii=False)

        system = textwrap.dedent(f"""\
            You are a Business Analyst assistant summarising graph query results.
            Domain: {self._schema.domain_name}
            Answer in plain, direct English. Be concise — 2-4 sentences max unless
            the user needs a list. Format lists with bullet points.
        """)
        user = (
            f"Original question: {question}\n\n"
            f"Query used:\n{query}\n\n"
            f"Raw results ({len(rows)} rows):\n{rows_text}\n\n"
            f"Write a clear answer to the question."
        )

        try:
            return call_llm(system, user, max_tokens=_FORMAT_MAX_TOKENS,
                            label="graph_query_format")
        except Exception:
            # Fallback: plain bullet list
            items = [r.get("label") or r.get("value") or str(r) for r in rows_preview]
            return "\n".join(f"• {item}" for item in items)

    # ── Schema / Prompt Builders ───────────────────────────────────────────────

    def _cypher_system_prompt(self) -> str:
        """
        System prompt for Cypher generation.
        Grounded on the *actual* schema so the LLM cannot hallucinate
        relationship types or node labels.
        """
        s = self._schema
        return textwrap.dedent(f"""\
            You are a Neo4j Cypher expert.  Generate Cypher queries for a system
            knowledge graph.

            SCHEMA
            ------
            Node labels   : {', '.join(s.node_labels)}
            Relationship  : {', '.join(s.rel_types)}
            Run ID filter : All nodes have run_id = '{s.run_id}'
                            Always add WHERE n.run_id = '{s.run_id}' (or equivalent)
                            to avoid returning nodes from other pipeline runs.

            RELATIONSHIP REFERENCE
            ----------------------
            (Actor)-[:ACTOR_PERFORMS]->(Flow)
            (Flow)-[:FLOW_IN_CONTEXT]->(BoundedContext)
            (Flow)-[:FLOW_USES]->(Page)
            (Flow)-[:FLOW_READS]->(Table)
            (Flow)-[:FLOW_WRITES]->(Table)
            (Feature)-[:FEATURE_INCLUDES]->(Flow)
            (Feature)-[:FEATURE_DEPENDS_ON]->(Entity)
            (Entity)-[:ENTITY_STORED_IN]->(Table)
            (Page)-[:PAGE_QUERIES]->(Table)
            (BoundedContext)-[:CONTEXT_CONTAINS]->(Feature)

            EXAMPLE NODES (use .label for human names, .id for exact matches)
            -------------
            {self._format_example_nodes()}

            RULES
            -----
            - Use CONTAINS or toLower() for partial name matching
            - Use the .label property for human-readable names in RETURN
            - Always filter by run_id to scope to this pipeline run
            - Return ONLY Cypher. No explanation. No markdown fences.

            EXAMPLE:
              Question: Which features depend on login?
              Answer:
              MATCH (feat:Feature)-[:FEATURE_INCLUDES]->(fl:Flow)-[:FLOW_USES]->(p:Page)
              WHERE toLower(p.label) CONTAINS 'login'
              AND feat.run_id = '{s.run_id}'
              RETURN DISTINCT feat.label AS feature
        """)

    def _json_filter_system_prompt(self) -> str:
        """
        System prompt for JSON filter generation (offline/no Neo4j).
        Uses the same schema but produces a traversal spec instead of Cypher.
        """
        s = self._schema
        edge_list = "\n".join(f"  {et}" for et in s.rel_types)
        node_list = "\n".join(f"  {nl.lower()}" for nl in s.node_labels)
        return textwrap.dedent(f"""\
            You produce JSON filter specs to traverse a knowledge graph stored as
            Python dicts {{nodes: [...], edges: [...]}}.

            SCHEMA
            ------
            Node types (use exact strings):
            {node_list}

            Edge types (use exact strings, lowercase):
            {', '.join(et.lower() for et in s.rel_types)}

            EDGE DIRECTIONS (source → target):
            (actor)-[actor_performs]->(flow)
            (flow)-[flow_in_context]->(bounded_context)
            (flow)-[flow_uses]->(page)
            (flow)-[flow_reads]->(table)
            (flow)-[flow_writes]->(table)
            (feature)-[feature_includes]->(flow)
            (feature)-[feature_depends_on]->(entity)
            (entity)-[entity_stored_in]->(table)
            (page)-[page_queries]->(table)
            (bounded_context)-[context_contains]->(feature)

            OUTPUT SCHEMA:
            {{
              "start_type":  "<node_type>",
              "start_label": "<case-insensitive substring to match on label>",
              "traverse": [
                {{"edge_type": "<edge_type>", "direction": "out"|"in"}},
                ...
              ],
              "return_type":  "<node_type to collect>",
              "return_field": "label"
            }}

            Return ONLY the JSON object. No explanation. No markdown.

            EXAMPLE:
              Question: Which features depend on login?
              Answer:
              {{"start_type":"page","start_label":"login",
                "traverse":[
                  {{"edge_type":"flow_uses","direction":"in"}},
                  {{"edge_type":"feature_includes","direction":"in"}}
                ],
                "return_type":"feature","return_field":"label"}}
        """)

    def _format_example_nodes(self) -> str:
        """Format example nodes for inclusion in the Cypher system prompt."""
        lines = []
        for n in self._schema.example_nodes:
            lines.append(f"  ({n['type']}  label='{n['label']}'  id='{n['id']}')")
        return "\n".join(lines) if lines else "  (none available)"

    # ── Initialisation Helpers ─────────────────────────────────────────────────

    def _load_graph(self) -> dict:
        with open(self._kg_path, "r", encoding="utf-8") as fh:
            return json.load(fh)

    def _extract_schema(self) -> GraphSchema:
        """
        Derive node labels, relationship types, and example nodes from
        the in-memory graph.  This is the ground truth the LLM is grounded on.
        """
        nodes = self._graph.get("nodes", [])
        edges = self._graph.get("edges", [])
        meta  = self._graph.get("meta",  {})

        # Neo4j labels are PascalCase versions of node types
        node_labels = sorted({
            _pascal(n["type"])
            for n in nodes
            if "type" in n
        })

        # Rel types are UPPER_SNAKE versions of edge types
        rel_types = sorted({
            e["type"].upper()
            for e in edges
            if "type" in e
        })

        # Pick representative example nodes: 1-2 per type
        type_seen: dict[str, int] = {}
        example_nodes: list[dict] = []
        for node in nodes:
            t = node.get("type", "")
            if type_seen.get(t, 0) < 2:
                example_nodes.append({
                    "id":    node["id"],
                    "label": node.get("label", node["id"]),
                    "type":  t,
                })
                type_seen[t] = type_seen.get(t, 0) + 1
            if len(example_nodes) >= _MAX_EXAMPLE_NODES:
                break

        return GraphSchema(
            node_labels   = node_labels,
            rel_types     = rel_types,
            example_nodes = example_nodes,
            run_id        = meta.get("run_id",     self._ctx.run_id),
            domain_name   = meta.get("domain",     ""),
        )

    def _detect_neo4j(self) -> tuple | None:
        """
        Return (uri, user, password, database) if NEO4J_URI is set,
        otherwise None (JSON fallback mode).
        """
        uri = os.environ.get("NEO4J_URI", "").strip()
        if not uri:
            return None
        user  = os.environ.get("NEO4J_USER",     "neo4j")
        passw = os.environ.get("NEO4J_PASSWORD",  "neo4j")
        db    = os.environ.get("NEO4J_DATABASE",  "neo4j")
        return (uri, user, passw, db)


# ── Utility ────────────────────────────────────────────────────────────────────

def _pascal(snake: str) -> str:
    """'bounded_context' → 'BoundedContext'"""
    return "".join(w.capitalize() for w in snake.split("_"))
